### ISSUE TITLE
Ensure that there is a blank line following all content

### ISSUE THREAD

**Issue by ForLoveOfCats** [JimmyCushnie/JECS#33]
As requested here is the issue to track this.

In the current LW beta all .succ files I have checked have content on the last line. While very minor is it generally good form to ensure at least one blank line at the end of a text file.

**Comment by JimmyCushnie** [comment]
I've seen both styles used intentionally. Perhaps this should be configurable, part of [FileStyle](https://github.com/JimmyCushnie/SUCC/wiki/File-Style)?
